### ISSUE TITLE
Issues with svc accounts

### ISSUE THREAD

**Issue by Emanuele94** [oatakan/ansible-collection-windows_sql_server#1]
Hi Oatakan,
first of all thanks a lot for your collection.
I'm having an issue on the installation part.
I'm using the install package and i'm not undestanding something on the variables i guess.
By following your readme:

> sql_server_svc_account_name: SASQLSvcAccount
> sql_server_agt_svc_account_name: SAAgtSvcAccount
> sql_server_svc_accounts_password: ''
> sql_server_local_users: false # set this to true to create local users instead of domain users

I've undestood that if i enable true the installation will create SASQLSvcAccount and SAAgtSvcAccount as local accounts.
My problem is that the playbook fails and if check logs on the win vm i see this:

Overall summary:
  Final result:                  Failed: see details below
  Exit code (Decimal):           -2061762559
  Exit facility code:            1308
  Exit error code:               1
  Exit message:                  Account 'SAAgtSvcAccount' provided for service 'SQLSERVERAGENT' does not exist. Provide an existing account name for the service.
  Start time:                    2023-05-29 13:44:46
  End time:                      2023-05-29 13:45:29
  Requested action:              Install

Setup completed with required actions for features.
Troubleshooting information for those features:
  Next step for SQLEngine:       SQL Server Setup was canceled before completing the operation. Try the setup process again.
  Next step for Replication:     SQL Server Setup was canceled before completing the operation. Try the setup process again.
  Next step for FullText:        SQL Server Setup was canceled before completing the operation. Try the setup process again.
  Next step for ComponentUpdate: SQL Server Setup was canceled before completing the operation. Try the setup process again.
  Next step for SNAC:            SQL Server Setup was canceled before completing the operation. Try the setup process again.
  Next step for SNAC_SDK:        SQL Server Setup was canceled before completing the operation. Try the setup process again.
  Next step for Writer:          SQL Server Setup was canceled before completing the operation. Try the setup process again.
  Next step for Browser:         SQL Server Setup was canceled before completing the operation. Try the setup process again.

I'm questioning my undestanding on the task at this point because i don't know if the accounts are being created or they have to be created before install

**Comment by oatakan** [comment]
I assume you want to install in standalone mode without joining a domain. In that case, if the local sql users don't exist, you should use the "sql_users" role before the "install" role. It will create the local users if sql_server_local_users: false. Hope this works for you.

**Comment by Emanuele94** [comment]
Yes i did exactly as you said and it worked.
Thanks! 
and thanks again for the collection!!!
